### ISSUE TITLE
Connection refused 127.0.0.1:3001

### ISSUE THREAD

**Issue by mtthidoteu** [UnicornTranscoder/UnicornTranscoder#120]
Hey guys!
I've been following the tutorial and everything is listed as being working, however my Plex container is giving me this error and streams won't start (no error, they just endlessly load)!
Cheers guys!

`message:
   'request to http://127.0.0.1:3001/api/ffmpeg failed, reason: connect ECONNREFUSED 127.0.0.1:3001',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }
{ FetchError: request to http://127.0.0.1:3001/api/ffmpeg failed, reason: connect ECONNREFUSED 127.0.0.1:3001
    at ClientRequest.<anonymous> (/snapshot/UnicornFFMPEG/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:189:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

**Comment by davidjameshowell** [comment]
@mtthidoteu  

Could you explain more about your setup? How is your Plex server and load balancer configured (in the same container, different container, etc).

**Comment by Maxou44** [comment]
It looks like a url misconfiguration
