### ISSUE TITLE
Can't set headers after they are sent

### ISSUE THREAD

**Issue by drouarb** [UnicornTranscoder/UnicornTranscoder#28]
```
Jul 31 13:52:03 citadel unicorn-transcoder[8276]: _http_outgoing.js:491
Jul 31 13:52:03 citadel unicorn-transcoder[8276]:     throw new Error('Can\'t set headers after they are sent.');
Jul 31 13:52:03 citadel unicorn-transcoder[8276]:     ^
Jul 31 13:52:03 citadel unicorn-transcoder[8276]: Error: Can't set headers after they are sent.
Jul 31 13:52:03 citadel unicorn-transcoder[8276]:     at validateHeader (_http_outgoing.js:491:11)
Jul 31 13:52:03 citadel unicorn-transcoder[8276]:     at ServerResponse.setHeader (_http_outgoing.js:498:3)
Jul 31 13:52:03 citadel unicorn-transcoder[8276]:     at ServerResponse.header (/root/unicorn/UnicornTranscoder/node_modules/express/lib/response.js:718:10)
Jul 31 13:52:03 citadel unicorn-transcoder[8276]:     at ServerResponse.send (/root/unicorn/UnicornTranscoder/node_modules/express/lib/response.js:163:12)
Jul 31 13:52:03 citadel unicorn-transcoder[8276]:     at universal.cache.(anonymous function).getChunk (/root/unicorn/UnicornTranscoder/core/dash.js:38:33)
Jul 31 13:52:03 citadel unicorn-transcoder[8276]:     at RedisClient.rc.on (/root/unicorn/UnicornTranscoder/core/transcoder.js:312:17)
Jul 31 13:52:03 citadel unicorn-transcoder[8276]:     at emitTwo (events.js:126:13)
Jul 31 13:52:03 citadel unicorn-transcoder[8276]:     at RedisClient.emit (events.js:214:7)
Jul 31 13:52:03 citadel unicorn-transcoder[8276]:     at return_pub_sub (/root/unicorn/UnicornTranscoder/node_modules/redis/index.js:786:18)
Jul 31 13:52:03 citadel unicorn-transcoder[8276]:     at RedisClient.return_reply (/root/unicorn/UnicornTranscoder/node_modules/redis/index.js:833:9)
```

**Comment by drouarb** [comment]
Fixed

**Comment by skhekare** [comment]
how fixed?
