### ISSUE TITLE
404 Error "Callback -2" (on video files) after 'start.mpd' has returned it's successful response

### ISSUE THREAD

**Issue by ned-kelly** [UnicornTranscoder/UnicornTranscoder#50]
Hi there guys,

I'm in the process of setting this up in a dockerised deployment (everything is up to the actual transcoder) which I'll push up to github once it's all working for others to easily deploy....

Currently as it stands:

- Environment is running behind Caddy reverse proxy for Lets Encrypt SSL's
- Loadbalancer & FFMpeg replacement components configured & working fine
- When the request to the `/video/:/transcode/universal/start.mpd` is intercepted by the load balancer and then 301'd to the actual transcode worker I get an initial response from the Load transcode worker (with the XML body as expected) however then when the Plex client requests the `initial.mp4` file I simply get the 404 response: `Callback -2` from UnicornTranscoder's Express.

Could anyone give me any feedback on what this may be / where to look?

I'm Currently running the latest commit in Master (so Version 2.0 I'm assuming)
Happy to share my Docker files also which might make it easier for developing.

Cheers,

**Comment by Maxou44** [comment]
Can you switch on `dev` branch for the transcoder and enable ffmpeg logs by adding `TRANSCODER_DEBUG=true` in your env?

Can you share Load balancer and Transcoder logs?

**Comment by ned-kelly** [comment]
Ok so the transcoder logs are as follows:

```
2019-03-21T07:51:14.386Z UnicornTranscoder:Dash l7na4fkglyehz7zm0ehp5aib
2019-03-21T07:51:14.386Z UnicornTranscoder:Transcoder Create transcoder l7na4fkglyehz7zm0ehp5aib
2019-03-21T07:51:14.387Z UnicornTranscoder:SessionManager save l7na4fkglyehz7zm0ehp5aib
2019-03-21T07:51:14.830Z UnicornTranscoder:Transcoder [ '-codec:1',
  'h264',
  '-codec:0',
  'dca',
  '-probesize',
  '10000000',
  '-i',
  '/nas/bay-7/TV/Top Gear/Season 23/Top Gear - S23E01 - Episode 1.mkv',
  '-filter_complex',
  '[0:1]scale=w=720:h=406[0];[0]format=pix_fmts=yuv420p|nv12[1]',
  '-filter_complex',
  '[0:0] aresample=async=1:ocl=\'stereo\':osr=48000[2]',
  '-map',
  '[1]',
  '-codec:0',
  'libx264',
  '-crf:0',
  '21',
  '-maxrate:0',
  '1724k',
  '-bufsize:0',
  '3448k',
  '-r:0',
  '25',
  '-preset:0',
  'veryfast',
  '-x264opts:0',
  'subme=2:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none',
  '-force_key_frames:0',
  'expr:gte(t,0+n_forced*8)',
  '-map',
  '[2]',
  '-metadata:s:1',
  'language=eng',
  '-codec:1',
  'aac',
  '-b:1',
  '162k',
  '-f',
  'dash',
  '-min_seg_duration',
  '8000000',
  '-skip_to_segment',
  '1',
  '-time_delta',
  '0.0625',
  '-manifest_name',
  'http://127.0.0.1:32400/video/:/transcode/session/l7na4fkglyehz7zm0ehp5aib/829c076b-7794-4fe5-88e5-bd73add4fcf8/manifest',
  '-avoid_negative_ts',
  'disabled',
  '-map_metadata',
  '-1',
  '-map_chapters',
  '-1',
  'dash',
  '-start_at_zero',
  '-copyts',
  '-vsync',
  'cfr',
  '-y',
  '-nostats',
  '-loglevel_plex',
  'error',
  '-progressurl',
  'http://127.0.0.1:32400/video/:/transcode/session/l7na4fkglyehz7zm0ehp5aib/04c5a9fc-258f-487d-9506-76b3b0df195f/progress' ]
2019-03-21T07:51:14.845Z UnicornTranscoder:Transcoder Spawn l7na4fkglyehz7zm0ehp5aib
2019-03-21T07:51:15.017Z UnicornTranscoder:Transcoder FFMPEG(stderr): { FetchError: request to http://127.0.0.1:3001/api/ffmpeg failed, reason: connect ECONNREFUSED 127.0.0.1:3001
    at ClientRequest.<anonymous> (/snapshot/UnicornFFMPEG/node_modules/node-fetch/lib/index.js:1444:11)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:382:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to http://127.0.0.1:3001/api/ffmpeg failed, reason: connect ECONNREFUSED 127.0.0.1:3001',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }
```

- Any reason why it's showing as: http://127.0.0.1:3001/api/ffmpeg **(That's wrong)** -- my `LOADBALANCER_ADDRESS` is actually configured as a totally different FQDN - Is it not reading the environment variable or has it changed?

**Comment by Maxou44** [comment]
Can you add load balancer and transcoders configurations? Something was misconfigured I think

**Comment by ned-kelly** [comment]
Yep sure,

**Transcoder:**
```
    environment:
      # Service configuration:
      - LOADBALANCER_ADDRESS=https://plex.xxxx/
      - INSTANCE_ADDRESS=https://tc1.plex.xxxx/
      - SERVER_LISTEN=0.0.0.0

      # These variables are used to automatically download the transcoder from plex - it needs to match the same version as whatever the main 'plex' container is running
      - PLEX_ARCH=linux-ubuntu-x86_64

      # Build should match whatever the tag is in our plex-core/Dockerfile
      - PLEX_BUILD=1.14.1.5488-cc260c476
      - CODECS_BUILD=531e313-1328
      - EAE_VERSION=141

      # Performance tuning (for this transcoder - Note if maxed out, other transcoders in the load balancer will get the traffic...)
      - MAX_SESSIONS=20
      - MAX_DOWNLOADS=10
      - MAX_TRANSCODE=10

      # If a session isn't requested for this amount of time (in second) the session will be deleted and transcoded files deleted.
      - TRANSCODER_DECAY_TIME=120
      # Send statistics about this worker's load every X seconds... (should be less than the load balancer's CUSTOM_SCORES_TIMEOUT variable)
      - PING_FREQUENCY=10

      # Uncomment to allow debugging
      - DEBUG=*
      - TRANSCODER_DEBUG=true
```

**Load Balancer:**
```
    environment:
      # Service configuration:
      - SERVER_PORT=3001
      - SERVER_HOST=127.0.0.1
      - SERVER_PUBLIC=https://plex.xxxx/
      - CUSTOM_DOWNLOAD_FORWARD=true

      # Plex service configuration/discovery
      - PLEX_HOST=plex
      - PLEX_PORT=32400
      - PLEX_PATH_USR=/usr/lib/plexmediaserver/

      # The path where Plex store sessions (to grab external subtitles) 
      - "PLEX_PATH_SESSIONS=/config/Library/Application Support/Plex Media Server/Cache/Transcode/Sessions"

      - DATABASE_MODE=sqlite
      - "DATABASE_SQLITE_PATH=/config/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db"

      - REDIS_HOST=plex-redis
      - REDIS_PORT=6379

      # How long (in seconds) before we remove a "transcode server" from the load balancer if it's offline...
      - CUSTOM_SCORES_TIMEOUT=20

      # Comma separated list of Plex Transcoders...
      - "CUSTOM_SERVERS_LIST=[https://tc1.plex.xxxx/,https://tc2.plex.xxxx/]"

      # Uncomment to allow debugging (if you're having issues)
      - DEBUG=*
```

**Comment by ned-kelly** [comment]
I'll push up the Docker Files also if you'd like to run them, would just like to get it all working ideally before I push it up :)

**Comment by drouarb** [comment]
Your output log shows `http://127.0.0.1:3001/api/ffmpeg` in the transcoder. This route is called by UnicornFFMPEG, it shouldn't be run by the transcoder. UnicornFFMPEG is a binary that should replace `Plex Transcoder` only in the Plex Media Server folder. It is used to push arguments to the UnicornLoadBalancer so the UnicornTranscoder can pull them to run the real Plex Transcoder on his side. Just remove the `plexmediaserver` in the UnicornTranscoder folder and run `npm run install` and everything should work fine.

**Comment by ned-kelly** [comment]
Yep - I'm aware of how the UnicornFFMPEG works - I've had to map the /usr/lib/plexmediaserver directory into my container (the Transcoder container) from the main Plex Container because it was not downloading the dependencies when starting for some reason (could be npm issue - will try yarn) - Glad a 2nd set of eyes helped, basically mapping them in is not going to cut it because the Transcoder has been changed and packaged up - i forgot about that 😃.

I'll post back with an update

**Comment by drouarb** [comment]
Be sure to run `npm run install` and because the install script is not triggered on `npm install` if you run as root

**Comment by ned-kelly** [comment]
> Be sure to run `npm run install` because the install script is not triggered on `npm install` if you run as root

Yep, just realised that - cheers

**Comment by ned-kelly** [comment]
Ok, so i'm one step closer - I'm now seeing a 404 with `Callback -1` in my response when I request `initial.mp4`... 

I'm getting the following in the Transcoder Logs:

```Thu, 21 Mar 2019 10:09:22 GMT express:router dispatching GET /video/:/transcode/universal/dash/waapgtycm0rv4b5dkfp2adca/1/initial.mp4
Thu, 21 Mar 2019 10:09:22 GMT express:router query  : /video/:/transcode/universal/dash/waapgtycm0rv4b5dkfp2adca/1/initial.mp4
Thu, 21 Mar 2019 10:09:22 GMT express:router expressInit  : /video/:/transcode/universal/dash/waapgtycm0rv4b5dkfp2adca/1/initial.mp4
Thu, 21 Mar 2019 10:09:22 GMT express:router corsMiddleware  : /video/:/transcode/universal/dash/waapgtycm0rv4b5dkfp2adca/1/initial.mp4
Thu, 21 Mar 2019 10:09:22 GMT express:router router  : /video/:/transcode/universal/dash/waapgtycm0rv4b5dkfp2adca/1/initial.mp4
Thu, 21 Mar 2019 10:09:22 GMT express:router dispatching GET /video/:/transcode/universal/dash/waapgtycm0rv4b5dkfp2adca/1/initial.mp4
2019-03-21T10:09:22.051Z UnicornTranscoder:SessionManager waapgtycm0rv4b5dkfp2adca not found, restarting (DASH)
2019-03-21T10:09:22.051Z UnicornTranscoder:Transcoder Create transcoder waapgtycm0rv4b5dkfp2adca
2019-03-21T10:09:22.051Z UnicornTranscoder:SessionManager save waapgtycm0rv4b5dkfp2adca
Thu, 21 Mar 2019 10:09:22 GMT express:router dispatching GET /
Thu, 21 Mar 2019 10:09:22 GMT express:router query  : /
Thu, 21 Mar 2019 10:09:22 GMT express:router expressInit  : /
Thu, 21 Mar 2019 10:09:22 GMT express:router corsMiddleware  : /
Thu, 21 Mar 2019 10:09:22 GMT express:router router  : /
Thu, 21 Mar 2019 10:09:22 GMT express:router dispatching GET /
Thu, 21 Mar 2019 10:09:22 GMT finalhandler default 404
2019-03-21T10:09:24.564Z UnicornTranscoder:Transcoder Failed to start waapgtycm0rv4b5dkfp2adca: StatusCodeError: 400 - "{\"error\":{\"code\":\"SESSION_TIMEOUT\",\"message\":\"The session wasn't launched in time, request fails\"}}"
2019-03-21T10:09:24.564Z UnicornTranscoder:SessionManager kill waapgtycm0rv4b5dkfp2adca
2019-03-21T10:09:24.564Z UnicornTranscoder:Transcoder Killing waapgtycm0rv4b5dkfp2adca
Thu, 21 Mar 2019 10:09:27 GMT express:router dispatching GET /
Thu, 21 Mar 2019 10:09:27 GMT express:router query  : /
Thu, 21 Mar 2019 10:09:27 GMT express:router expressInit  : /
Thu, 21 Mar 2019 10:09:27 GMT express:router corsMiddleware  : /
Thu, 21 Mar 2019 10:09:27 GMT express:router router  : /
Thu, 21 Mar 2019 10:09:27 GMT express:router dispatching GET /
Thu, 21 Mar 2019 10:09:27 GMT finalhandler default 404```

- FWIW I'm not sure if this is related to the `PLEX_PATH_SESSIONS` environment but it is set & my Load Balancer DOES has access to the Plex sessions (shared between Plex and the transcoder in `/config/Library/Application Support/Plex Media Server/Cache/Transcode/Sessions`) however I'm not seeing any files created in this directory when I start playing a file.

**Comment by Maxou44** [comment]
`/config/Library/Application Support/Plex Media Server/Cache/Transcode/Sessions` don't need to be shared with the transcoder, only between Plex and the LoadBalancer

```
2019-03-21T10:09:24.564Z UnicornTranscoder:Transcoder Failed to start waapgtycm0rv4b5dkfp2adca: StatusCodeError: 400 - "{\"error\":{\"code\":\"SESSION_TIMEOUT\",\"message\":\"The session wasn't launched in time, request fails\"}}"
```
It means, the UnicornFFMPEG didn't sent arguments to the load balancer, in general it's because UnicornFFMPEG wasn't setup or it don't have access to the load balanacer (URL configuration)
