### ISSUE TITLE
Spawn error when lauching UnicornTranscoder.

### ISSUE THREAD

**Issue by ruCyberPoison** [UnicornTranscoder/UnicornTranscoder#60]
Command: SERVER_PORT=3001 npm start

```
{ Error: spawn /root/UnicornTranscoder/codecs/EasyAudioEncoder-eae-69c1de6-25-amd64/EasyAudioEncoder/EasyAudioEncoder ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /root/UnicornTranscoder/codecs/EasyAudioEncoder-eae-69c1de6-25-amd64/EasyAudioEncoder/EasyAudioEncoder',
  path: '/root/UnicornTranscoder/codecs/EasyAudioEncoder-eae-69c1de6-25-amd64/EasyAudioEncoder/EasyAudioEncoder',
  spawnargs: [] }
```

**Comment by Maxou44** [comment]
```npm run install``` ?

**Comment by ruCyberPoison** [comment]
Yes i forget it, 
Now is running but the plex web says
```
Conversion failed. The transcoder exited due to an error.
```

Using the port 3001 web interface. 
Everything in local (Same machine) so i don't run cluster or paralel servers. I'm Just tried to install and put it working. 

All is under 127.0.0.1 (Default configs)

**Comment by Maxou44** [comment]
Can you share configurations?

**Comment by ruCyberPoison** [comment]
How i redirect the plex web app to the transcoder ?
what configuragations you need ?

**Comment by Maxou44** [comment]
Normaly when you start the stream you will see a 302 in the devtools
